project_dir: '{PROJECT_NAME}'
project_dir: './projects'
movie_path: './movies/{PATH_TO_VIDEO_FILE}.mp4'
plot_filename: 'plot.txt'
movie_id: '0063350' # ID for Night of the living dead
device: cpu # usually one of (cpu, cuda, mps)
tts_model_id: 'tts_models/multilingual/multi-dataset/xtts_v2'
tts_language: en
reference_void_path: './voices/{PATH_TO_REFERENCE_VOICE_FILE}.wav'
n_audios: 1
n_screenshot: 1000
similarity_model_id: 'clip-ViT-B-32'
n_retrieved_images: 1
similarity_batch_size: 128
min_clip_len: 5
clip_volume: 0.5 # 50% of the original clip volume
voice_volume: 1.0 # 100% of the generated voice volume