movie_path: 'movies/night_of_the_living_dead.mp4'
movie_id: '0063350'
reference_voice_path: './voices/sample_voice.wav'
project_name: night_of_the_living_dead
project_dir: './projects'
plot_filename: 'plot.txt'
device: cpu
tts_model_id: 'tts_models/multilingual/multi-dataset/xtts_v2'
tts_language: en
n_audios: 1
n_frames: 1000
similarity_model_id: 'clip-ViT-B-32'
n_retrieved_images: 1
similarity_batch_size: 128
min_clip_len: 5
clip_volume: 0.5
voice_volume: 1.0